### ISSUE TITLE
ring description is misleading/wrong

### ISSUE THREAD

**Issue by ericonr** [The-DevX-Initiative/RCIG_Coordination_Repo#17]
> Collection of cryptographic primitives, written in pure Rust

ring is heavily based on BoringSSL. That means C and assembly are present all across the code base, and I'd assume are unlikely to be removed any time soon, given the performance benefits they bring.

I'm not sure what part of the library "pure Rust" refers to, but it definitely isn't the whole thing.

**Comment by tarcieri** [comment]
Indeed. Not sure how that got in there, but I'll update it with a description taken verbatim from *ring*'s documentation

**Comment by tarcieri** [comment]
See #20
