### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by skaunov** [The-DevX-Initiative/RCIG_Coordination_Repo#78]
Link to https://github.com/RustCrypto/stream-ciphers/tree/master/ctr leads to page-404.
https://github.com/The-DevX-Initiative/RCIG_Coordination_Repo/blob/f67a9a78c97f89550073e619dfb188e42e0e18bd/Awesome_Rust_Cryptography.md?plain=1#L246

**Comment by rozbb** [comment]
Good catch. Correct link is https://github.com/RustCrypto/block-modes/tree/master/ctr
