### ISSUE TITLE
Awesome Rust Cryptography: [Add THFE-rs library to the FHE list]

### ISSUE THREAD

**Issue by zaccherinij** [The-DevX-Initiative/RCIG_Coordination_Repo#80]
Proposition:
Category: Fully Homomorphic Encryption
Library name: TFHE-rs
Desc: TFHE-rs: Pure Rust implementation of the TFHE scheme for boolean and integers FHE arithmetics
Author: Zama

**Comment by tarcieri** [comment]
Looks interesting and well-maintained. Open a PR?

**Comment by tarcieri** [comment]
That's a different repo than this one?

**Comment by zaccherinij** [comment]
My bad. Created the PR here: https://github.com/The-DevX-Initiative/RCIG_Coordination_Repo/pull/81
Thank you!

**Comment by tarcieri** [comment]
Added in #81
